### ISSUE TITLE
unused imports

### ISSUE THREAD

**Issue by pmazzini** [hedhyw/go-import-lint#3]
Just out of curiosity, is there some standard for leaving unused imports in a separate block?
I don't see it in https://github.com/golang/go/wiki/CodeReviewComments#imports

I also tried searching in the Go codebase and it is a bit inconsistent. E.g.
https://cs.opensource.google/go/go/+/refs/tags/go1.19.1:src/time/time.go;l=83

Related to #1 #2

**Comment by hedhyw** [comment]
Unused imports usually should have explanation comments that naturally move them into separate blocks.

_Actually, we can add the flag, that makes this optional._
