### ISSUE TITLE
ioutil deprecated

### ISSUE THREAD

**Issue by AdrianCio** [hedhyw/go-import-lint#5]
Hey, I cannot use the lib anymore with a newer version of golang because of :

SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.

The fix is just to replace in `walker.go`
```
var files []os.FileInfo
	files, err = io.ReadDir(path)
```
with
```
var files []os.DirEntry
	files, err = os.ReadDir(path)
```

Can you please update the lib ?

**Comment by Kryvchun** [comment]
Sure

**Comment by hedhyw** [comment]
Sure

**Comment by hedhyw** [comment]
Please, try v1.1.2

`go install github.com/hedhyw/go-import-lint/cmd/go-import-lint@v1.1.2`
